/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    { pattern: /bg-phase-(1|2|3|4|5|6|7|8)(\/(5|10|15|20))?/ },
    { pattern: /text-phase-(1|2|3|4|5|6|7|8)/ },
    { pattern: /border-phase-(1|2|3|4|5|6|7|8)/ },
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#173d00',
        secondary: '#506442',
        tertiary: '#735c00',
        linen: '#fbf9f8',
        surface: '#f9faf0',
        'surface-bright': '#f9faf0',
        'surface-dim': '#d9dbd1',
        'surface-variant': '#e1e3d9',
        'surface-container': '#edefe5',
        'surface-container-low': '#f3f5ea',
        'surface-container-high': '#e7e9df',
        'surface-container-highest': '#e1e3d9',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#191d16',
        'on-surface-variant': '#42493c',
        'on-background': '#191d16',
        'primary-container': '#29560d',
        'on-primary-container': '#96cb75',
        'secondary-container': '#d2eabf',
        'on-secondary-container': '#566a48',
        'tertiary-container': '#cca830',
        'on-tertiary-container': '#4f3e00',
        'primary-fixed': '#bbf297',
        'primary-fixed-dim': '#a0d57e',
        'secondary-fixed': '#d2eabf',
        'secondary-fixed-dim': '#b7cea4',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e9c34a',
        outline: '#73796b',
        'outline-variant': '#c2c9b8',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e312b',
        'inverse-on-surface': '#f0f2e7',
        'inverse-primary': '#a0d57e',
        'surface-tint': '#3b6a20',
        gold: '#fed65b',
        'phase-1': '#8397b8',
        'phase-2': '#735c00',
        'phase-3': '#4b5f7e',
        'phase-4': '#ba1a1a',
        'phase-5': '#334865',
        'phase-6': '#e9c349',
        'phase-7': '#021a35',
        'phase-8': '#574500',
      },
      spacing: {
        'container-margin': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        unit: '8px',
        'section-gap': '48px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-scripture': ['32px', { lineHeight: '44px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        grace: '0 4px 20px rgba(26, 47, 75, 0.06)',
        'grace-up': '0 -4px 20px rgba(26, 47, 75, 0.06)',
      },
      borderRadius: {
        xl: '0.75rem',
      },
    },
  },
  plugins: [],
};
