#!/usr/bin/env node
/**
 * Compose agent context files from AGENT.md + agent-rules + role-specific tails.
 * Usage: node scripts/lib/compose-context.mjs [--check]
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "../../..");
const MANIFEST_PATH = join(ROOT, ".github/agent-manifest.json");
const GENERATED_HEADER =
  "<!-- AUTO-GENERATED by npm run agent:compose — edit AGENT.md, agent-rules/, or agent-overrides/ instead -->\n\n";

async function readRoot(relativePath) {
  return readFile(join(ROOT, relativePath), "utf-8");
}

function stripTopHeading(markdown) {
  return markdown.replace(/^#\s+.+\n+/, "");
}

async function composeEntry(manifest, outputPath, entry) {
  const parts = [GENERATED_HEADER, entry.title + "\n"];

  if (entry.includeAgentGuide) {
    const agent = await readRoot(manifest.agentGuide);
    parts.push("---\n\n## Repository guide\n\n", stripTopHeading(agent));
  }

  for (const ruleName of entry.rules ?? []) {
    const ruleFile = ruleName.endsWith(".md") ? ruleName : `${ruleName}.md`;
    const rulePath = join(manifest.rulesDir, ruleFile);
    const ruleContent = await readFile(join(ROOT, rulePath), "utf-8");
    parts.push("\n---\n\n", ruleContent.trim(), "\n");
  }

  if (entry.tail) {
    const tailContent = await readFile(
      join(ROOT, manifest.overridesDir, entry.tail),
      "utf-8"
    );
    parts.push("\n---\n\n", tailContent.trim(), "\n");
  }

  return { outputPath, content: parts.join("").trimEnd() + "\n" };
}

async function main() {
  const checkMode = process.argv.includes("--check");
  const manifest = JSON.parse(await readFile(MANIFEST_PATH, "utf-8"));
  const results = [];

  for (const [outputPath, entry] of Object.entries(manifest.outputs)) {
    const { content } = await composeEntry(manifest, outputPath, entry);
    const fullPath = join(ROOT, outputPath);

    if (checkMode) {
      let existing;
      try {
        existing = await readFile(fullPath, "utf-8");
      } catch {
        console.error(`Missing composed file: ${outputPath} — run npm run agent:compose`);
        process.exit(1);
      }
      if (existing !== content) {
        console.error(`Drift detected: ${outputPath} — run npm run agent:compose`);
        process.exit(1);
      }
      results.push(outputPath);
      continue;
    }

    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, content, "utf-8");
    console.log("Composed", outputPath);
  }

  if (checkMode) {
    console.log(`All ${results.length} composed context files are up to date.`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
